"""PDF export with correct Arabic rendering.

Arabic needs two things most PDF libraries get wrong:

1. **Shaping** – letters change form depending on their neighbours
   (isolated/initial/medial/final) and form ligatures such as لا.
2. **Bidirectional layout** – Arabic runs right-to-left while embedded
   English words and numbers run left-to-right.

fpdf2 delegates shaping to HarfBuzz (``uharfbuzz``) – the same engine used by
Chrome and Firefox – and implements the Unicode Bidirectional Algorithm, so
the output is identical to what a browser would show. The Amiri font (SIL Open
Font License) is embedded; it covers Arabic *and* Latin so mixed text never
falls back to empty boxes.
"""

from __future__ import annotations

import io
import logging
import unicodedata
from dataclasses import dataclass, replace
from datetime import datetime
from pathlib import Path

from fpdf import FPDF
from fpdf.enums import XPos, YPos

from .errors import AppError, ErrorCode

GITHUB_URL = "https://github.com/AhmadNedal/LocalWhisper"
GITHUB_LABEL = "github.com/AhmadNedal/LocalWhisper"
# GitHub's mark (Octicons "mark-github", MIT), drawn as a vector.
GITHUB_MARK_SVG = (
    b'<svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 16 16">'
    b'<path fill="#24292f" d="M8 0C3.58 0 0 3.58 0 8c0 3.54 2.29 6.53 5.47 7.59.4.07.55-.17.55-.38 '
    b'0-.19-.01-.82-.01-1.49-2.01.37-2.53-.49-2.69-.94-.09-.23-.48-.94-.82-1.13-.28-.15-.68-.52-.01-.53'
    b'.63-.01 1.08.58 1.23.82.72 1.21 1.87.87 2.33.66.07-.52.28-.87.51-1.07-1.78-.2-3.64-.89-3.64-3.95 '
    b'0-.87.31-1.59.82-2.15-.08-.2-.36-1.02.08-2.12 0 0 .67-.21 2.2.82.64-.18 1.32-.27 2-.27.68 0 1.36.09 '
    b'2 .27 1.53-1.04 2.2-.82 2.2-.82.44 1.1.16 1.92.08 2.12.51.56.82 1.27.82 2.15 0 3.07-1.87 3.75-3.65 '
    b'3.95.29.25.54.73.54 1.48 0 1.07-.01 1.93-.01 2.2 0 .21.15.46.55.38A8.013 8.013 0 0016 8c0-4.42-3.58-8-8-8z"/>'
    b'</svg>'
)

log = logging.getLogger(__name__)

APP_LABEL = "Local Transcriber"

# Palette (RGB)
NAVY = (15, 61, 110)
ACCENT = (31, 111, 178)
ACCENT_SOFT = (232, 241, 250)
BAND_SUB = (170, 200, 232)
CARD_FILL = (246, 248, 251)
CARD_EDGE = (224, 231, 240)
INK = (22, 27, 34)
MUTED = (110, 120, 134)
RULE = (221, 227, 235)
ALT_INK = (52, 84, 122)

_LABELS = {
    "ar": {
        "title": "تفريغ نصي",
        "file": "الملف",
        "source": "المصدر",
        "date": "تاريخ التفريغ",
        "language": "اللغة",
        "model": "النموذج",
        "duration": "المدة",
        "words": "عدد الكلمات",
        "segments": "المقاطع",
        "paragraphs": "الفقرات",
        "engine": "طريقة التفريغ",
        "engine_local": "محليًا على الجهاز",
        "engine_cloud": "خدمة سحابية",
        "engine_youtube": "ترجمة يوتيوب",
        "transcript": "النص",
        "minute": "الدقيقة {time}",
        "summary": "الملخص",
        "translation": "الترجمة",
        "transcript_both": "النص والترجمة",
        "key_points": "النقاط الرئيسية",
        "chapters": "الفصول",
        "ai_note": "هذا الملخص مُولَّد بالذكاء الاصطناعي ({model}) — راجِعه قبل الاعتماد عليه.",
        "page": "صفحة {page} من {total}",
    },
    "en": {
        "title": "Transcript",
        "file": "File",
        "source": "Source",
        "date": "Transcribed on",
        "language": "Language",
        "model": "Model",
        "duration": "Duration",
        "words": "Words",
        "segments": "Segments",
        "paragraphs": "Paragraphs",
        "engine": "Method",
        "engine_local": "On this device",
        "engine_cloud": "Cloud service",
        "engine_youtube": "YouTube captions",
        "transcript": "Transcript",
        "minute": "Minute {time}",
        "summary": "Summary",
        "translation": "Translation",
        "transcript_both": "Transcript & translation",
        "key_points": "Key points",
        "chapters": "Chapters",
        "ai_note": "This summary was generated by AI ({model}) — review it before relying on it.",
        "page": "Page {page} of {total}",
    },
}


@dataclass
class ExportSegment:
    start: float
    end: float
    text: str
    alt: str = ""  # translation printed under the text (bilingual PDF)


@dataclass
class ExportRequest:
    output_path: Path
    media_name: str
    language_code: str
    language_name: str
    model_name: str | None
    duration: float | None
    include_timestamps: bool
    ui_language: str  # "ar" | "en" – language of the PDF's labels
    segments: list[ExportSegment]
    transcribed_at: datetime
    source: str = ""  # shown (as a link) only when it is a web URL, never a local path
    engine: str = "local"  # "local" | "cloud" | "youtube"
    summary: dict | None = None  # AI summary: summary, key_points, chapters[{start,title,summary}]
    translation: list[ExportSegment] | None = None  # same order as the non-empty segments
    translation_language_name: str = ""
    content: str = "original"  # original | translation | both


def format_timestamp(seconds: float) -> str:
    seconds = max(0, int(round(seconds)))
    h, rem = divmod(seconds, 3600)
    m, s = divmod(rem, 60)
    return f"{h:02d}:{m:02d}:{s:02d}"


def format_clock(seconds: float, long: bool) -> str:
    """Compact timestamp: ``mm:ss`` for short media, ``h:mm:ss`` otherwise."""
    seconds = max(0, int(seconds))
    h, rem = divmod(seconds, 3600)
    m, s = divmod(rem, 60)
    return f"{h}:{m:02d}:{s:02d}" if long else f"{m:02d}:{s:02d}"


def section_interval(duration: float) -> int:
    """Seconds between the "minute" markers in the body (0 = no markers)."""
    if duration < 600:
        return 0
    if duration <= 3600:
        return 300
    if duration <= 7200:
        return 600
    return 900


def is_rtl(text: str) -> bool:
    """Paragraph direction from the first strong character (Unicode bidi rule P2)."""
    for ch in text:
        bidi = unicodedata.bidirectional(ch)
        if bidi in ("R", "AL"):
            return True
        if bidi == "L":
            return False
    return False


def build_paragraphs(segments: list[ExportSegment], gap: float = 2.0, max_chars: int = 700) -> list[ExportSegment]:
    """Merge consecutive segments into readable paragraphs (used without timestamps).

    A new paragraph starts after a pause longer than ``gap`` seconds, or when
    the current one is long and the previous segment ended a sentence.
    """
    paragraphs: list[ExportSegment] = []
    current: ExportSegment | None = None
    for seg in segments:
        text = seg.text.strip()
        if not text:
            continue
        if current is None:
            current = ExportSegment(seg.start, seg.end, text, seg.alt.strip())
            continue
        ends_sentence = current.text.endswith((".", "؟", "?", "!", "…"))
        if seg.start - current.end > gap or (len(current.text) > max_chars and ends_sentence):
            paragraphs.append(current)
            current = ExportSegment(seg.start, seg.end, text, seg.alt.strip())
        else:
            current.text = f"{current.text} {text}"
            current.alt = f"{current.alt} {seg.alt.strip()}".strip()
            current.end = seg.end
    if current is not None:
        paragraphs.append(current)
    return paragraphs


def _content_segments(req: "ExportRequest", content: str) -> list[ExportSegment]:
    """Segments to print: the original, the translation, or both (translation as ``alt``)."""
    base = [s for s in req.segments if s.text.strip()]
    trans = req.translation or []
    if content == "translation":
        return [ExportSegment(t.start, t.end, t.text) for t in trans if t.text.strip()]
    if content == "both":
        if len(trans) == len(base):
            pairs = zip(base, trans)
        else:  # edited transcript: match each segment with the translation closest in time
            pairs = ((s, min(trans, key=lambda t, s=s: abs(t.start - s.start))) for s in base) if trans else ()
        return [ExportSegment(s.start, s.end, s.text, t.text.strip()) for s, t in pairs]
    return base


def _body_events(
    segments: list[ExportSegment], chapters: list[dict], timestamps: bool
) -> list[ExportSegment | dict]:
    """Transcript items with chapter headings inserted where each chapter starts.

    In reading mode, paragraphs never cross a chapter boundary.
    """
    segs = [s for s in segments if s.text.strip()]
    if not chapters:
        return list(segs if timestamps else build_paragraphs(segs))
    events: list[ExportSegment | dict] = []
    bounds = [c["start"] for c in chapters[1:]] + [float("inf")]
    # Anything before the first chapter belongs to it.
    groups: list[list[ExportSegment]] = [[] for _ in chapters]
    gi = 0
    for seg in segs:
        while seg.start >= bounds[gi] - 0.01:
            gi += 1
        groups[gi].append(seg)
    for ch, group in zip(chapters, groups):
        if not group:
            continue
        events.append(ch)
        events.extend(group if timestamps else build_paragraphs(group))
    return events


class _TranscriptPDF(FPDF):
    def __init__(self, labels: dict[str, str], ui_rtl: bool, title: str, date: str, total_pages: int | None) -> None:
        super().__init__(orientation="portrait", unit="mm", format="A4")
        self.labels = labels
        self.total_pages = total_pages
        self.ui_rtl = ui_rtl
        self.doc_title = title
        self.date_text = date
        self.set_margins(left=18, top=24, right=18)
        self.set_auto_page_break(auto=True, margin=22)
        self.set_title(f"{title} — {labels['title']}")
        self.set_subject(labels["title"])
        self.set_creator(APP_LABEL)
        self.set_producer(APP_LABEL)
        self.set_lang("ar" if ui_rtl else "en")

    # Direction must be set before every piece of text so HarfBuzz shapes it right.
    def use_direction(self, text: str, fallback: bool | None = None) -> bool:
        rtl = is_rtl(text) if text.strip() else (self.ui_rtl if fallback is None else fallback)
        self.set_text_shaping(use_shaping_engine=True, direction="rtl" if rtl else "ltr")
        return rtl

    def fit(self, text: str, width: float) -> str:
        """Shorten ``text`` with an ellipsis until it fits ``width`` in the current font."""
        if self.get_string_width(text) <= width:
            return text
        while len(text) > 4 and self.get_string_width(text + "…") > width:
            text = text[:-1]
        return text.rstrip() + "…"

    def fit_size(self, text: str, width: float, style: str, size: float, min_size: float) -> float:
        """Largest font size in [min_size, size] at which ``text`` fits, then select it."""
        while size > min_size:
            self.set_font("Amiri", style, size)
            if self.get_string_width(text) <= width:
                return size
            size -= 0.5
        self.set_font("Amiri", style, min_size)
        return min_size

    @property
    def start_align(self) -> str:
        return "R" if self.ui_rtl else "L"

    @property
    def end_align(self) -> str:
        return "L" if self.ui_rtl else "R"

    def header(self) -> None:
        # Thin brand strip on every page; page 1 draws its full band in _layout.
        self.set_fill_color(*NAVY)
        self.rect(0, 0, self.w, 3, style="F")
        if self.page_no() == 1:
            return
        body_w = self.w - self.l_margin - self.r_margin
        self.set_y(8)
        self.set_font("Amiri", "B", 9.5)
        self.set_text_color(*NAVY)
        self.use_direction(self.doc_title)
        self.set_x(self.l_margin)
        self.cell(body_w, 6, self.fit(self.doc_title, body_w * 0.7), align=self.start_align)
        self.set_font("Amiri", "", 9)
        self.set_text_color(*MUTED)
        self.use_direction(self.labels["title"])
        self.set_x(self.l_margin)
        self.cell(body_w, 6, self.labels["title"], align=self.end_align)
        self.set_draw_color(*RULE)
        self.set_line_width(0.3)
        self.line(self.l_margin, 15.5, self.w - self.r_margin, 15.5)
        self.set_y(self.t_margin)
        self.set_text_color(*INK)

    def footer(self) -> None:
        body_w = self.w - self.l_margin - self.r_margin
        y = self.h - 14
        self.set_draw_color(*RULE)
        self.set_line_width(0.3)
        self.line(self.l_margin, y, self.w - self.r_margin, y)
        self.set_font("Amiri", "", 8.5)
        self.set_text_color(*MUTED)
        # The total is known from a first layout pass (see generate_pdf). fpdf2's
        # "{nb}" alias can't be used: shaped RTL text no longer contains it.
        page = self.labels["page"].format(page=self.page_no(), total=self.total_pages or self.page_no())
        for text, align in ((page, "C"), (self.date_text, self.end_align)):
            self.use_direction(text)
            self.set_xy(self.l_margin, y + 1.5)
            self.cell(body_w, 6, text, align=align)
        self.set_text_color(*INK)


def generate_pdf(req: ExportRequest, fonts_dir: Path) -> Path:
    try:
        # Two passes: the first only measures how many pages the layout needs
        # so the footer can say "page X of Y" in Arabic.
        total = _layout(req, fonts_dir, None).pages_count
        pdf = _layout(req, fonts_dir, total)
        req.output_path.parent.mkdir(parents=True, exist_ok=True)
        tmp = req.output_path.with_suffix(".pdf.part")
        pdf.output(str(tmp))
        tmp.replace(req.output_path)  # atomic: never leave a half-written PDF
        return req.output_path
    except AppError:
        raise
    except PermissionError as exc:
        raise AppError(ErrorCode.PDF_FAILED, f"Cannot write to {req.output_path} (is it open in another program?)") from exc
    except Exception as exc:  # noqa: BLE001
        log.exception("PDF generation failed")
        raise AppError(ErrorCode.PDF_FAILED, f"{exc.__class__.__name__}: {exc}"[:300]) from exc


def _layout(req: ExportRequest, fonts_dir: Path, total_pages: int | None) -> _TranscriptPDF:
    regular = fonts_dir / "Amiri-Regular.ttf"
    bold = fonts_dir / "Amiri-Bold.ttf"
    if not regular.is_file():
        raise AppError(ErrorCode.PDF_FAILED, f"Arabic font missing: {regular}")

    labels = _LABELS.get(req.ui_language, _LABELS["ar"])
    ui_rtl = req.ui_language == "ar"
    content = req.content if req.translation and req.content in ("translation", "both") else "original"
    req = replace(req, segments=_content_segments(req, content))
    sample = " ".join(s.text for s in req.segments[:20])
    doc_rtl = is_rtl(sample) if sample.strip() else ui_rtl
    web_source = req.source.strip() if req.source.strip().lower().startswith(("http://", "https://")) else ""
    ext = Path(req.media_name).suffix
    # Local files: drop the extension from the title (it stays on the "File" line).
    title = req.media_name[: -len(ext)] if not web_source and 1 < len(ext) <= 6 and ext[1:].isalnum() else req.media_name
    title = title.strip() or req.media_name
    date_text = req.transcribed_at.strftime("%Y-%m-%d  %H:%M")

    pdf = _TranscriptPDF(labels, ui_rtl, title, date_text, total_pages)
    pdf.add_font("Amiri", "", str(regular))
    pdf.add_font("Amiri", "B", str(bold if bold.is_file() else regular))
    pdf.add_page()

    left = pdf.l_margin
    body_w = pdf.w - pdf.l_margin - pdf.r_margin
    start_align = pdf.start_align

    # ---- Title band --------------------------------------------------------
    band_h = 44
    pdf.set_fill_color(*NAVY)
    pdf.rect(0, 0, pdf.w, band_h, style="F")
    pdf.set_fill_color(*ACCENT)
    pdf.rect(0, band_h, pdf.w, 1.4, style="F")

    kicker = labels["title"]
    pdf.set_font("Amiri", "", 10)
    pdf.set_text_color(*BAND_SUB)
    pdf.use_direction(kicker)
    pdf.set_xy(left, 9)
    pdf.cell(body_w, 6, kicker, align=start_align)

    pdf.fit_size(title, body_w, "B", 21, 14)
    pdf.set_text_color(255, 255, 255)
    pdf.use_direction(title)
    pdf.set_xy(left, 16.5)
    pdf.cell(body_w, 12, pdf.fit(title, body_w), align=start_align)

    pdf.set_font("Amiri", "", 10)
    pdf.set_text_color(*BAND_SUB)
    subline = f"{labels['date']}: {date_text}"
    pdf.use_direction(subline, ui_rtl)
    pdf.set_xy(left, 30)
    pdf.cell(body_w, 6, subline, align=start_align)

    # ---- Summary cards -----------------------------------------------------
    summary = req.summary or {}
    chapters = sorted(
        (
            {"start": float(c.get("start") or 0), "title": str(c.get("title") or "").strip(), "summary": str(c.get("summary") or "").strip()}
            for c in (summary.get("chapters") or [])
            if isinstance(c, dict) and str(c.get("title") or "").strip()
        ),
        key=lambda c: c["start"],
    )
    events = _body_events(req.segments, chapters, req.include_timestamps)
    items = [e for e in events if isinstance(e, ExportSegment)]
    words = sum(len(s.text.split()) for s in req.segments)
    engine_key = f"engine_{req.engine}" if f"engine_{req.engine}" in labels else "engine_local"

    cards: list[tuple[str, str]] = []
    if req.duration:
        cards.append((labels["duration"], format_timestamp(req.duration)))
    language_value = req.language_name or req.language_code or "—"
    if content == "translation" and req.translation_language_name:
        language_value = req.translation_language_name
    elif content == "both" and req.translation_language_name:
        language_value = f"{language_value} · {req.translation_language_name}"
    cards.append((labels["language"], language_value))
    cards.append((labels["words"], f"{words:,}"))
    cards.append((labels["segments" if req.include_timestamps else "paragraphs"], f"{len(items):,}"))
    if req.model_name:
        cards.append((labels["model"], req.model_name))
    cards.append((labels["engine"], labels[engine_key]))

    cols, gap, card_h = 3, 4.0, 17.0
    card_w = (body_w - gap * (cols - 1)) / cols
    y0 = band_h + 9
    for i, (label, value) in enumerate(cards):
        row, col = divmod(i, cols)
        # RTL documents fill the grid from the right, like the text.
        x = left + (cols - 1 - col) * (card_w + gap) if ui_rtl else left + col * (card_w + gap)
        y = y0 + row * (card_h + gap)
        pdf.set_fill_color(*CARD_FILL)
        pdf.set_draw_color(*CARD_EDGE)
        pdf.set_line_width(0.25)
        pdf.rect(x, y, card_w, card_h, style="DF", round_corners=True, corner_radius=2.5)
        pdf.set_fill_color(*ACCENT)
        edge_x = x + card_w - 1.6 if ui_rtl else x + 0.6
        pdf.rect(edge_x, y + 4, 1.0, card_h - 8, style="F", round_corners=True, corner_radius=0.5)

        inner = card_w - 9
        ix = x + 3.5 if ui_rtl else x + 5.5
        pdf.set_font("Amiri", "", 8.5)
        pdf.set_text_color(*MUTED)
        pdf.use_direction(label, ui_rtl)
        pdf.set_xy(ix, y + 2.2)
        pdf.cell(inner, 5, label, align=start_align)

        pdf.fit_size(value, inner, "B", 12, 8.5)
        pdf.set_text_color(*NAVY)
        pdf.use_direction(value, ui_rtl)
        pdf.set_xy(ix, y + 7.8)
        pdf.cell(inner, 7, pdf.fit(value, inner), align=start_align)

    rows = (len(cards) + cols - 1) // cols
    y = y0 + rows * card_h + (rows - 1) * gap + 5

    # ---- File / source lines -----------------------------------------------
    lines: list[tuple[str, str, str | None]] = (
        [(labels["source"], web_source, web_source)] if web_source else [(labels["file"], req.media_name, None)]
    )
    label_w = 22
    for label, value, link in lines:
        lx = left + body_w - label_w if ui_rtl else left
        vx = left if ui_rtl else left + label_w
        pdf.set_font("Amiri", "B", 9.5)
        pdf.set_text_color(*MUTED)
        pdf.use_direction(label, ui_rtl)
        pdf.set_xy(lx, y)
        pdf.cell(label_w, 6, f"{label}:", align=start_align)
        pdf.set_font("Amiri", "", 9.5)
        pdf.set_text_color(*(ACCENT if link else INK))
        pdf.use_direction(value, ui_rtl)
        pdf.set_xy(vx, y)
        pdf.cell(body_w - label_w, 6, pdf.fit(value, body_w - label_w - 2), align=start_align, link=link or "")
        y += 6.5

    long_media = (req.duration or (items[-1].end if items else 0)) >= 3600
    chapter_links = [pdf.add_link() for _ in chapters]

    def heading(text: str, y: float, size: float = 15, bookmark: bool = True) -> float:
        pdf.set_font("Amiri", "B", size)
        pdf.set_text_color(*NAVY)
        pdf.use_direction(text, ui_rtl)
        pdf.set_xy(left, y)
        if bookmark:
            pdf.start_section(text)
        pdf.cell(body_w, 9, text, align=start_align)
        head_w = pdf.get_string_width(text)
        pdf.set_fill_color(*ACCENT)
        pdf.rect(left + body_w - head_w if ui_rtl else left, y + 9.3, head_w, 0.9, style="F")
        pdf.set_draw_color(*RULE)
        pdf.set_line_width(0.3)
        pdf.line(left, y + 9.75, left + body_w, y + 9.75)
        return y + 14

    def ensure(space: float) -> None:
        if pdf.get_y() + space > pdf.page_break_trigger:
            pdf.add_page()

    def paragraph(text: str, size: float, lh: float, x: float, w: float, color=INK, style: str = "") -> None:  # noqa: ANN001
        pdf.set_font("Amiri", style, size)
        pdf.set_text_color(*color)
        rtl = pdf.use_direction(text, ui_rtl)
        pdf.set_x(x)
        pdf.multi_cell(w, lh, text, align="R" if rtl else "L", new_x=XPos.LMARGIN, new_y=YPos.NEXT)

    def time_badge(x: float, y: float, w: float, stamp: str) -> None:
        pdf.set_fill_color(*ACCENT_SOFT)
        pdf.rect(x, y + 1.3, w, 5.6, style="F", round_corners=True, corner_radius=2.8)
        pdf.set_font("Amiri", "B", 8.5)
        pdf.set_text_color(*ACCENT)
        pdf.set_text_shaping(use_shaping_engine=True, direction="ltr")
        pdf.set_xy(x, y + 1.2)
        pdf.cell(w, 5.8, stamp, align="C")

    badge_w = 19 if long_media else 15

    # ---- AI summary (optional) ---------------------------------------------
    summary_text = str(summary.get("summary") or "").strip()
    key_points = [str(k).strip() for k in (summary.get("key_points") or []) if str(k).strip()]
    if summary_text or key_points or chapters:
        pdf.page_mode = "USE_OUTLINES"
        pdf.set_y(heading(labels["summary"], y + 5))
        for para in [p for p in summary_text.split("\n") if p.strip()]:
            ensure(9)
            paragraph(para.strip(), 12.5, 8.4, left, body_w)
            pdf.ln(2.5)

        if key_points:
            ensure(24)
            pdf.set_y(heading(labels["key_points"], pdf.get_y() + 4, size=13, bookmark=False))
            indent = 6
            for point in key_points:
                ensure(8.5)
                py = pdf.get_y()
                pdf.set_fill_color(*ACCENT)
                dot_x = left + body_w - 2.6 if ui_rtl else left + 0.8
                pdf.ellipse(dot_x, py + 3.3, 1.8, 1.8, style="F")
                paragraph(point, 12, 7.8, left if ui_rtl else left + indent, body_w - indent)
                pdf.ln(1.2)

        if chapters:
            ensure(24)
            pdf.set_y(heading(labels["chapters"], pdf.get_y() + 4, size=13, bookmark=False))
            text_w_ch = body_w - badge_w - 4
            for i, ch in enumerate(chapters):
                ensure(15)
                cy = pdf.get_y()
                bx = left + body_w - badge_w if ui_rtl else left
                time_badge(bx, cy, badge_w, format_clock(ch["start"], long_media))
                tx = left if ui_rtl else left + badge_w + 4
                pdf.set_font("Amiri", "B", 12)
                pdf.set_text_color(*NAVY)
                title_txt = f"{i + 1}. {ch['title']}"
                pdf.use_direction(title_txt, ui_rtl)
                pdf.set_xy(tx, cy)
                pdf.multi_cell(
                    text_w_ch, 8, title_txt, align=start_align, new_x=XPos.LMARGIN, new_y=YPos.NEXT, link=chapter_links[i]
                )
                if ch["summary"]:
                    pdf.set_y(pdf.get_y() - 0.5)
                    paragraph(ch["summary"], 10.5, 6.6, tx, text_w_ch, color=MUTED)
                pdf.ln(2.2)

        model_name = str(summary.get("model") or summary.get("provider_name") or "AI")
        note = labels["ai_note"].format(model=model_name)
        ensure(10)
        pdf.ln(1)
        paragraph(note, 9, 6, left, body_w, color=MUTED)
        # Start the transcript on a fresh page unless most of this one is still free.
        if pdf.page_break_trigger - pdf.get_y() < 110:
            pdf.add_page()
            y = pdf.get_y() - 5
        else:
            y = pdf.get_y() + 6

    # ---- Transcript heading ------------------------------------------------
    body_title = {"original": labels["transcript"], "translation": labels["translation"], "both": labels["transcript_both"]}[content]
    pdf.set_y(heading(body_title, y + 5) + 1)

    # ---- Transcript body ---------------------------------------------------
    ts = req.include_timestamps
    # Reading layout: slightly larger type and airier lines, like a printed article.
    body_size = 12.5 if ts else 13.5
    line_h = 8.0 if ts else 9.2
    text_w = body_w - (badge_w + 4 if ts else 0)
    # Chapters (from the AI summary) replace the fixed "minute" markers.
    interval = 0 if chapters else (section_interval(req.duration or 0) if ts else 0)
    next_marker = interval
    if interval:
        pdf.page_mode = "USE_OUTLINES"  # open the bookmarks panel: one per section

    for event in events:
        if isinstance(event, dict):
            # Chapter heading from the summary (+ bookmark, + target of the TOC link).
            idx = chapters.index(event)
            ensure(14 + line_h)
            cy = pdf.get_y() + (4 if pdf.get_y() > pdf.t_margin + 12 else 0)
            label = event["title"]
            pdf.set_link(chapter_links[idx], y=cy, page=pdf.page_no())
            pdf.set_xy(left, cy)
            pdf.start_section(label, level=1)
            if ts:
                # Segments already carry their own time badges: mark the chapter with a bar.
                pdf.set_fill_color(*ACCENT)
                pdf.rect(left + body_w - 1.2 if ui_rtl else left, cy + 1.5, 1.2, 6, style="F")
                tx, tw = (left, body_w - 4) if ui_rtl else (left + 4, body_w - 4)
            else:
                time_badge(left + body_w - badge_w if ui_rtl else left, cy + 0.6, badge_w, format_clock(event["start"], long_media))
                tx, tw = (left, body_w - badge_w - 4) if ui_rtl else (left + badge_w + 4, body_w - badge_w - 4)
            pdf.set_font("Amiri", "B", 13)
            pdf.set_text_color(*NAVY)
            pdf.use_direction(label, ui_rtl)
            pdf.set_xy(tx, cy)
            pdf.multi_cell(tw, 9, label, align=start_align, new_x=XPos.LMARGIN, new_y=YPos.NEXT)
            ly = pdf.get_y() + 0.5
            pdf.set_draw_color(*RULE)
            pdf.set_line_width(0.3)
            pdf.line(left, ly, left + body_w, ly)
            pdf.set_y(ly + 3)
            continue

        item = event
        text = item.text.strip()
        if interval and item.start >= next_marker:
            # Section marker ("Minute 05:00") + PDF bookmark for quick navigation.
            while item.start >= next_marker + interval:
                next_marker += interval
            ensure(9 + line_h)
            my = pdf.get_y() + 1.5
            marker = labels["minute"].format(time=format_clock(next_marker, long_media))
            pdf.set_font("Amiri", "B", 10)
            pdf.set_text_color(*ACCENT)
            pdf.use_direction(marker, ui_rtl)
            pdf.set_xy(left, my)
            pdf.start_section(marker, level=1)
            pdf.cell(body_w, 6, marker, align=start_align)
            mw = pdf.get_string_width(marker) + 3
            pdf.set_draw_color(*RULE)
            pdf.set_line_width(0.3)
            if ui_rtl:
                pdf.line(left, my + 3, left + body_w - mw, my + 3)
            else:
                pdf.line(left + mw, my + 3, left + body_w, my + 3)
            pdf.set_y(my + 8)
            next_marker += interval

        ensure(line_h)
        rtl = is_rtl(text)
        y = pdf.get_y()
        if ts:
            time_badge(left + body_w - badge_w if doc_rtl else left, y, badge_w, format_clock(item.start, long_media))
            text_x = left if doc_rtl else left + badge_w + 4
        else:
            text_x = left

        pdf.set_font("Amiri", "", body_size)
        pdf.set_text_color(*INK)
        pdf.use_direction(text)
        pdf.set_xy(text_x, y)
        pdf.multi_cell(text_w, line_h, text, align="R" if rtl else "L", new_x=XPos.LMARGIN, new_y=YPos.NEXT)
        if item.alt:
            # Translation under the original, smaller and softer.
            alt_rtl = pdf.use_direction(item.alt)
            pdf.set_font("Amiri", "", body_size - 1.5)
            pdf.set_text_color(*ALT_INK)
            pdf.use_direction(item.alt)
            pdf.set_x(text_x)
            pdf.multi_cell(
                text_w, line_h - 1.2, item.alt, align="R" if alt_rtl else "L", new_x=XPos.LMARGIN, new_y=YPos.NEXT
            )
            pdf.ln(1.5)
        pdf.ln(1.8 if ts else 5)

    # ---- Closing mark: the project's GitHub page (clickable) ---------------
    if pdf.get_y() + 16 > pdf.page_break_trigger:
        pdf.add_page()
    pdf.ln(5)
    y = pdf.get_y()
    pdf.set_draw_color(*RULE)
    pdf.set_line_width(0.3)
    pdf.line(left + body_w * 0.3, y, left + body_w * 0.7, y)
    size = 6.5
    pdf.set_font("Amiri", "", 8.5)
    label_w = pdf.get_string_width(GITHUB_LABEL)
    gap = 2
    x = left + (body_w - (size + gap + label_w)) / 2
    top = y + 3
    pdf.image(io.BytesIO(GITHUB_MARK_SVG), x=x, y=top, w=size, h=size, link=GITHUB_URL)
    pdf.set_text_color(*MUTED)
    pdf.set_xy(x + size + gap, top + (size - 5) / 2)
    pdf.cell(label_w + 1, 5, GITHUB_LABEL, link=GITHUB_URL)
    pdf.link(x, top, size + gap + label_w, size, GITHUB_URL)
    pdf.set_text_color(*INK)
    return pdf
