"""PDF export with correct Arabic rendering.

Arabic needs two things most PDF libraries get wrong:

1. **Shaping** – letters change form depending on their neighbours
   (isolated/initial/medial/final) and form ligatures such as لا.
2. **Bidirectional layout** – Arabic runs right-to-left while embedded
   English words and numbers run left-to-right.

fpdf2 delegates shaping to HarfBuzz (``uharfbuzz``) – the same engine used by
Chrome and Firefox – and implements the Unicode Bidirectional Algorithm, so
the output is identical to what a browser would show. The Amiri font (SIL Open
Font License) is embedded; it covers Arabic *and* Latin so mixed text never
falls back to empty boxes.
"""

from __future__ import annotations

import logging
import unicodedata
from dataclasses import dataclass
from datetime import datetime
from pathlib import Path

from fpdf import FPDF
from fpdf.enums import XPos, YPos

from .errors import AppError, ErrorCode

log = logging.getLogger(__name__)

APP_LABEL = "Local Transcriber"

# Palette (RGB)
NAVY = (15, 61, 110)
ACCENT = (31, 111, 178)
ACCENT_SOFT = (232, 241, 250)
BAND_SUB = (170, 200, 232)
CARD_FILL = (246, 248, 251)
CARD_EDGE = (224, 231, 240)
INK = (22, 27, 34)
MUTED = (110, 120, 134)
RULE = (221, 227, 235)

_LABELS = {
    "ar": {
        "title": "تفريغ نصي",
        "file": "الملف",
        "source": "المصدر",
        "date": "تاريخ التفريغ",
        "language": "اللغة",
        "model": "النموذج",
        "duration": "المدة",
        "words": "عدد الكلمات",
        "segments": "المقاطع",
        "paragraphs": "الفقرات",
        "engine": "طريقة التفريغ",
        "engine_local": "محليًا على الجهاز",
        "engine_cloud": "خدمة سحابية",
        "engine_youtube": "ترجمة يوتيوب",
        "transcript": "النص",
        "minute": "الدقيقة {time}",
        "page": "صفحة {page} من {total}",
        "generated": "أُنشئ محليًا بواسطة Local Transcriber — لم تُرفع أي بيانات",
        "generated_cloud": "أُنشئ بواسطة Local Transcriber — فُرّغ الصوت عبر خدمة سحابية اختارها المستخدم",
        "generated_youtube": "أُنشئ بواسطة Local Transcriber — النص مأخوذ من ترجمة يوتيوب المتاحة للفيديو",
    },
    "en": {
        "title": "Transcript",
        "file": "File",
        "source": "Source",
        "date": "Transcribed on",
        "language": "Language",
        "model": "Model",
        "duration": "Duration",
        "words": "Words",
        "segments": "Segments",
        "paragraphs": "Paragraphs",
        "engine": "Method",
        "engine_local": "On this device",
        "engine_cloud": "Cloud service",
        "engine_youtube": "YouTube captions",
        "transcript": "Transcript",
        "minute": "Minute {time}",
        "page": "Page {page} of {total}",
        "generated": "Generated locally by Local Transcriber — no data was uploaded",
        "generated_cloud": "Generated by Local Transcriber — audio was transcribed by a cloud service chosen by the user",
        "generated_youtube": "Generated by Local Transcriber — text taken from the video's YouTube captions",
    },
}


@dataclass
class ExportSegment:
    start: float
    end: float
    text: str


@dataclass
class ExportRequest:
    output_path: Path
    media_name: str
    language_code: str
    language_name: str
    model_name: str | None
    duration: float | None
    include_timestamps: bool
    ui_language: str  # "ar" | "en" – language of the PDF's labels
    segments: list[ExportSegment]
    transcribed_at: datetime
    source: str = ""  # shown (as a link) only when it is a web URL, never a local path
    engine: str = "local"  # "local" | "cloud" | "youtube"


def format_timestamp(seconds: float) -> str:
    seconds = max(0, int(round(seconds)))
    h, rem = divmod(seconds, 3600)
    m, s = divmod(rem, 60)
    return f"{h:02d}:{m:02d}:{s:02d}"


def format_clock(seconds: float, long: bool) -> str:
    """Compact timestamp: ``mm:ss`` for short media, ``h:mm:ss`` otherwise."""
    seconds = max(0, int(seconds))
    h, rem = divmod(seconds, 3600)
    m, s = divmod(rem, 60)
    return f"{h}:{m:02d}:{s:02d}" if long else f"{m:02d}:{s:02d}"


def section_interval(duration: float) -> int:
    """Seconds between the "minute" markers in the body (0 = no markers)."""
    if duration < 600:
        return 0
    if duration <= 3600:
        return 300
    if duration <= 7200:
        return 600
    return 900


def is_rtl(text: str) -> bool:
    """Paragraph direction from the first strong character (Unicode bidi rule P2)."""
    for ch in text:
        bidi = unicodedata.bidirectional(ch)
        if bidi in ("R", "AL"):
            return True
        if bidi == "L":
            return False
    return False


def build_paragraphs(segments: list[ExportSegment], gap: float = 2.0, max_chars: int = 700) -> list[ExportSegment]:
    """Merge consecutive segments into readable paragraphs (used without timestamps).

    A new paragraph starts after a pause longer than ``gap`` seconds, or when
    the current one is long and the previous segment ended a sentence.
    """
    paragraphs: list[ExportSegment] = []
    current: ExportSegment | None = None
    for seg in segments:
        text = seg.text.strip()
        if not text:
            continue
        if current is None:
            current = ExportSegment(seg.start, seg.end, text)
            continue
        ends_sentence = current.text.endswith((".", "؟", "?", "!", "…"))
        if seg.start - current.end > gap or (len(current.text) > max_chars and ends_sentence):
            paragraphs.append(current)
            current = ExportSegment(seg.start, seg.end, text)
        else:
            current.text = f"{current.text} {text}"
            current.end = seg.end
    if current is not None:
        paragraphs.append(current)
    return paragraphs


class _TranscriptPDF(FPDF):
    def __init__(self, labels: dict[str, str], ui_rtl: bool, title: str, date: str, total_pages: int | None) -> None:
        super().__init__(orientation="portrait", unit="mm", format="A4")
        self.labels = labels
        self.total_pages = total_pages
        self.ui_rtl = ui_rtl
        self.doc_title = title
        self.date_text = date
        self.set_margins(left=18, top=24, right=18)
        self.set_auto_page_break(auto=True, margin=22)
        self.set_title(f"{title} — {labels['title']}")
        self.set_subject(labels["title"])
        self.set_creator(APP_LABEL)
        self.set_producer(APP_LABEL)
        self.set_lang("ar" if ui_rtl else "en")

    # Direction must be set before every piece of text so HarfBuzz shapes it right.
    def use_direction(self, text: str, fallback: bool | None = None) -> bool:
        rtl = is_rtl(text) if text.strip() else (self.ui_rtl if fallback is None else fallback)
        self.set_text_shaping(use_shaping_engine=True, direction="rtl" if rtl else "ltr")
        return rtl

    def fit(self, text: str, width: float) -> str:
        """Shorten ``text`` with an ellipsis until it fits ``width`` in the current font."""
        if self.get_string_width(text) <= width:
            return text
        while len(text) > 4 and self.get_string_width(text + "…") > width:
            text = text[:-1]
        return text.rstrip() + "…"

    def fit_size(self, text: str, width: float, style: str, size: float, min_size: float) -> float:
        """Largest font size in [min_size, size] at which ``text`` fits, then select it."""
        while size > min_size:
            self.set_font("Amiri", style, size)
            if self.get_string_width(text) <= width:
                return size
            size -= 0.5
        self.set_font("Amiri", style, min_size)
        return min_size

    @property
    def start_align(self) -> str:
        return "R" if self.ui_rtl else "L"

    @property
    def end_align(self) -> str:
        return "L" if self.ui_rtl else "R"

    def header(self) -> None:
        # Thin brand strip on every page; page 1 draws its full band in _layout.
        self.set_fill_color(*NAVY)
        self.rect(0, 0, self.w, 3, style="F")
        if self.page_no() == 1:
            return
        body_w = self.w - self.l_margin - self.r_margin
        self.set_y(8)
        self.set_font("Amiri", "B", 9.5)
        self.set_text_color(*NAVY)
        self.use_direction(self.doc_title)
        self.set_x(self.l_margin)
        self.cell(body_w, 6, self.fit(self.doc_title, body_w * 0.7), align=self.start_align)
        self.set_font("Amiri", "", 9)
        self.set_text_color(*MUTED)
        self.use_direction(self.labels["title"])
        self.set_x(self.l_margin)
        self.cell(body_w, 6, self.labels["title"], align=self.end_align)
        self.set_draw_color(*RULE)
        self.set_line_width(0.3)
        self.line(self.l_margin, 15.5, self.w - self.r_margin, 15.5)
        self.set_y(self.t_margin)
        self.set_text_color(*INK)

    def footer(self) -> None:
        body_w = self.w - self.l_margin - self.r_margin
        y = self.h - 14
        self.set_draw_color(*RULE)
        self.set_line_width(0.3)
        self.line(self.l_margin, y, self.w - self.r_margin, y)
        self.set_font("Amiri", "", 8.5)
        self.set_text_color(*MUTED)
        # The total is known from a first layout pass (see generate_pdf). fpdf2's
        # "{nb}" alias can't be used: shaped RTL text no longer contains it.
        page = self.labels["page"].format(page=self.page_no(), total=self.total_pages or self.page_no())
        for text, align in ((APP_LABEL, self.start_align), (page, "C"), (self.date_text, self.end_align)):
            self.use_direction(text)
            self.set_xy(self.l_margin, y + 1.5)
            self.cell(body_w, 6, text, align=align)
        self.set_text_color(*INK)


def generate_pdf(req: ExportRequest, fonts_dir: Path) -> Path:
    try:
        # Two passes: the first only measures how many pages the layout needs
        # so the footer can say "page X of Y" in Arabic.
        total = _layout(req, fonts_dir, None).pages_count
        pdf = _layout(req, fonts_dir, total)
        req.output_path.parent.mkdir(parents=True, exist_ok=True)
        tmp = req.output_path.with_suffix(".pdf.part")
        pdf.output(str(tmp))
        tmp.replace(req.output_path)  # atomic: never leave a half-written PDF
        return req.output_path
    except AppError:
        raise
    except PermissionError as exc:
        raise AppError(ErrorCode.PDF_FAILED, f"Cannot write to {req.output_path} (is it open in another program?)") from exc
    except Exception as exc:  # noqa: BLE001
        log.exception("PDF generation failed")
        raise AppError(ErrorCode.PDF_FAILED, f"{exc.__class__.__name__}: {exc}"[:300]) from exc


def _layout(req: ExportRequest, fonts_dir: Path, total_pages: int | None) -> _TranscriptPDF:
    regular = fonts_dir / "Amiri-Regular.ttf"
    bold = fonts_dir / "Amiri-Bold.ttf"
    if not regular.is_file():
        raise AppError(ErrorCode.PDF_FAILED, f"Arabic font missing: {regular}")

    labels = _LABELS.get(req.ui_language, _LABELS["ar"])
    ui_rtl = req.ui_language == "ar"
    sample = " ".join(s.text for s in req.segments[:20])
    doc_rtl = is_rtl(sample) if sample.strip() else ui_rtl
    web_source = req.source.strip() if req.source.strip().lower().startswith(("http://", "https://")) else ""
    ext = Path(req.media_name).suffix
    # Local files: drop the extension from the title (it stays on the "File" line).
    title = req.media_name[: -len(ext)] if not web_source and 1 < len(ext) <= 6 and ext[1:].isalnum() else req.media_name
    title = title.strip() or req.media_name
    date_text = req.transcribed_at.strftime("%Y-%m-%d  %H:%M")

    pdf = _TranscriptPDF(labels, ui_rtl, title, date_text, total_pages)
    pdf.add_font("Amiri", "", str(regular))
    pdf.add_font("Amiri", "B", str(bold if bold.is_file() else regular))
    pdf.add_page()

    left = pdf.l_margin
    body_w = pdf.w - pdf.l_margin - pdf.r_margin
    start_align = pdf.start_align

    # ---- Title band --------------------------------------------------------
    band_h = 44
    pdf.set_fill_color(*NAVY)
    pdf.rect(0, 0, pdf.w, band_h, style="F")
    pdf.set_fill_color(*ACCENT)
    pdf.rect(0, band_h, pdf.w, 1.4, style="F")

    kicker = f"{labels['title']}  ·  {APP_LABEL}"
    pdf.set_font("Amiri", "", 10)
    pdf.set_text_color(*BAND_SUB)
    pdf.use_direction(kicker)
    pdf.set_xy(left, 9)
    pdf.cell(body_w, 6, kicker, align=start_align)

    pdf.fit_size(title, body_w, "B", 21, 14)
    pdf.set_text_color(255, 255, 255)
    pdf.use_direction(title)
    pdf.set_xy(left, 16.5)
    pdf.cell(body_w, 12, pdf.fit(title, body_w), align=start_align)

    pdf.set_font("Amiri", "", 10)
    pdf.set_text_color(*BAND_SUB)
    subline = f"{labels['date']}: {date_text}"
    pdf.use_direction(subline, ui_rtl)
    pdf.set_xy(left, 30)
    pdf.cell(body_w, 6, subline, align=start_align)

    # ---- Summary cards -----------------------------------------------------
    items = req.segments if req.include_timestamps else build_paragraphs(req.segments)
    items = [i for i in items if i.text.strip()]
    words = sum(len(s.text.split()) for s in req.segments)
    engine_key = f"engine_{req.engine}" if f"engine_{req.engine}" in labels else "engine_local"

    cards: list[tuple[str, str]] = []
    if req.duration:
        cards.append((labels["duration"], format_timestamp(req.duration)))
    cards.append((labels["language"], req.language_name or req.language_code or "—"))
    cards.append((labels["words"], f"{words:,}"))
    cards.append((labels["segments" if req.include_timestamps else "paragraphs"], f"{len(items):,}"))
    if req.model_name:
        cards.append((labels["model"], req.model_name))
    cards.append((labels["engine"], labels[engine_key]))

    cols, gap, card_h = 3, 4.0, 17.0
    card_w = (body_w - gap * (cols - 1)) / cols
    y0 = band_h + 9
    for i, (label, value) in enumerate(cards):
        row, col = divmod(i, cols)
        # RTL documents fill the grid from the right, like the text.
        x = left + (cols - 1 - col) * (card_w + gap) if ui_rtl else left + col * (card_w + gap)
        y = y0 + row * (card_h + gap)
        pdf.set_fill_color(*CARD_FILL)
        pdf.set_draw_color(*CARD_EDGE)
        pdf.set_line_width(0.25)
        pdf.rect(x, y, card_w, card_h, style="DF", round_corners=True, corner_radius=2.5)
        pdf.set_fill_color(*ACCENT)
        edge_x = x + card_w - 1.6 if ui_rtl else x + 0.6
        pdf.rect(edge_x, y + 4, 1.0, card_h - 8, style="F", round_corners=True, corner_radius=0.5)

        inner = card_w - 9
        ix = x + 3.5 if ui_rtl else x + 5.5
        pdf.set_font("Amiri", "", 8.5)
        pdf.set_text_color(*MUTED)
        pdf.use_direction(label, ui_rtl)
        pdf.set_xy(ix, y + 2.2)
        pdf.cell(inner, 5, label, align=start_align)

        pdf.fit_size(value, inner, "B", 12, 8.5)
        pdf.set_text_color(*NAVY)
        pdf.use_direction(value, ui_rtl)
        pdf.set_xy(ix, y + 7.8)
        pdf.cell(inner, 7, pdf.fit(value, inner), align=start_align)

    rows = (len(cards) + cols - 1) // cols
    y = y0 + rows * card_h + (rows - 1) * gap + 5

    # ---- File / source lines -----------------------------------------------
    lines: list[tuple[str, str, str | None]] = (
        [(labels["source"], web_source, web_source)] if web_source else [(labels["file"], req.media_name, None)]
    )
    label_w = 22
    for label, value, link in lines:
        lx = left + body_w - label_w if ui_rtl else left
        vx = left if ui_rtl else left + label_w
        pdf.set_font("Amiri", "B", 9.5)
        pdf.set_text_color(*MUTED)
        pdf.use_direction(label, ui_rtl)
        pdf.set_xy(lx, y)
        pdf.cell(label_w, 6, f"{label}:", align=start_align)
        pdf.set_font("Amiri", "", 9.5)
        pdf.set_text_color(*(ACCENT if link else INK))
        pdf.use_direction(value, ui_rtl)
        pdf.set_xy(vx, y)
        pdf.cell(body_w - label_w, 6, pdf.fit(value, body_w - label_w - 2), align=start_align, link=link or "")
        y += 6.5

    # ---- Transcript heading ------------------------------------------------
    y += 5
    pdf.set_font("Amiri", "B", 15)
    pdf.set_text_color(*NAVY)
    pdf.use_direction(labels["transcript"], ui_rtl)
    pdf.set_xy(left, y)
    pdf.start_section(labels["transcript"])
    pdf.cell(body_w, 9, labels["transcript"], align=start_align)
    head_w = pdf.get_string_width(labels["transcript"])
    pdf.set_fill_color(*ACCENT)
    bar_x = left + body_w - head_w if ui_rtl else left
    pdf.rect(bar_x, y + 9.3, head_w, 0.9, style="F")
    pdf.set_draw_color(*RULE)
    pdf.set_line_width(0.3)
    pdf.line(left, y + 9.75, left + body_w, y + 9.75)
    pdf.set_y(y + 15)

    # ---- Transcript body ---------------------------------------------------
    ts = req.include_timestamps
    # Reading layout: slightly larger type and airier lines, like a printed article.
    body_size = 12.5 if ts else 13.5
    line_h = 8.0 if ts else 9.2
    long_media = (req.duration or (items[-1].end if items else 0)) >= 3600
    badge_w = 19 if long_media else 15
    text_w = body_w - (badge_w + 4 if ts else 0)
    interval = section_interval(req.duration or 0) if ts else 0
    next_marker = interval
    if interval:
        pdf.page_mode = "USE_OUTLINES"  # open the bookmarks panel: one per section

    for item in items:
        text = item.text.strip()

        if interval and item.start >= next_marker:
            # Section marker ("Minute 05:00") + PDF bookmark for quick navigation.
            while item.start >= next_marker + interval:
                next_marker += interval
            if pdf.get_y() + 9 + line_h > pdf.page_break_trigger:
                pdf.add_page()
            my = pdf.get_y() + 1.5
            marker = labels["minute"].format(time=format_clock(next_marker, long_media))
            pdf.set_font("Amiri", "B", 10)
            pdf.set_text_color(*ACCENT)
            pdf.use_direction(marker, ui_rtl)
            pdf.set_xy(left, my)
            pdf.start_section(marker, level=1)
            pdf.cell(body_w, 6, marker, align=start_align)
            mw = pdf.get_string_width(marker) + 3
            pdf.set_draw_color(*RULE)
            pdf.set_line_width(0.3)
            if ui_rtl:
                pdf.line(left, my + 3, left + body_w - mw, my + 3)
            else:
                pdf.line(left + mw, my + 3, left + body_w, my + 3)
            pdf.set_y(my + 8)
            next_marker += interval

        if pdf.get_y() + line_h > pdf.page_break_trigger:
            pdf.add_page()
        rtl = is_rtl(text)
        y = pdf.get_y()

        if ts:
            stamp = format_clock(item.start, long_media)
            bx = left + body_w - badge_w if doc_rtl else left
            pdf.set_fill_color(*ACCENT_SOFT)
            pdf.rect(bx, y + 1.3, badge_w, 5.6, style="F", round_corners=True, corner_radius=2.8)
            pdf.set_font("Amiri", "B", 8.5)
            pdf.set_text_color(*ACCENT)
            pdf.set_text_shaping(use_shaping_engine=True, direction="ltr")
            pdf.set_xy(bx, y + 1.2)
            pdf.cell(badge_w, 5.8, stamp, align="C")
            text_x = left if doc_rtl else left + badge_w + 4
        else:
            text_x = left

        pdf.set_font("Amiri", "", body_size)
        pdf.set_text_color(*INK)
        pdf.use_direction(text)
        pdf.set_xy(text_x, y)
        pdf.multi_cell(text_w, line_h, text, align="R" if rtl else "L", new_x=XPos.LMARGIN, new_y=YPos.NEXT)
        pdf.ln(1.8 if ts else 5)

    # ---- Closing note ------------------------------------------------------
    note = labels.get(f"generated_{req.engine}", labels["generated"]) if req.engine != "local" else labels["generated"]
    if pdf.get_y() + 14 > pdf.page_break_trigger:
        pdf.add_page()
    pdf.ln(4)
    y = pdf.get_y()
    pdf.set_draw_color(*RULE)
    pdf.set_line_width(0.3)
    pdf.line(left + body_w * 0.3, y, left + body_w * 0.7, y)
    pdf.set_font("Amiri", "", 8.5)
    pdf.set_text_color(*MUTED)
    pdf.use_direction(note)
    pdf.set_xy(left, y + 2)
    pdf.cell(body_w, 6, note, align="C", new_x=XPos.LMARGIN, new_y=YPos.NEXT)
    return pdf
